/**
 * Generated by apidoc - http://www.apidoc.me
 * Service version: 0.1.9-dev
 * apidoc:0.11.21 http://www.apidoc.me/trifectalabs/raven/0.1.9-dev/play_2_x_json
 */
package com.trifectalabs.raven.v0.models {

  /**
   * Effort zones of an activity
   */
  case class ActivityZones(
    activityID: _root_.java.util.UUID,
    zoneType: com.trifectalabs.raven.v0.models.ZoneType,
    zoneOne: Int,
    zoneTwo: Int,
    zoneThree: Int,
    zoneFour: Int,
    zoneFive: Int
  )

  /**
   * Object used to respond to health checks
   */
  case class HealthCheck(
    status: String
  )

  /**
   * An activity in a training plan for a user. Distance/Time/Elevation can be left
   * out of user defined activities to be filled in by the training plan builder.
   */
  case class TrainingPlanActivity(
    id: _root_.java.util.UUID,
    userID: _root_.java.util.UUID,
    activityType: com.trifectalabs.osprey.v0.models.ActivityType,
    distance: _root_.scala.Option[Double] = None,
    time: _root_.scala.Option[Double] = None,
    elevation: _root_.scala.Option[Double] = None,
    activityID: _root_.scala.Option[_root_.java.util.UUID] = None,
    calendarEventID: _root_.scala.Option[String] = None,
    polyline: _root_.scala.Option[String] = None,
    scheduledAt: _root_.scala.Option[_root_.org.joda.time.DateTime] = None,
    createdAt: _root_.org.joda.time.DateTime
  )

  /**
   * Training zone with upper and lower bounds
   */
  case class TrainingZone(
    lower: Double,
    upper: Double
  )

  /**
   * Zones used to determine effort of an activity
   */
  case class TrainingZones(
    userID: _root_.java.util.UUID,
    zoneType: com.trifectalabs.raven.v0.models.ZoneType,
    zoneOne: com.trifectalabs.raven.v0.models.TrainingZone,
    zoneTwo: com.trifectalabs.raven.v0.models.TrainingZone,
    zoneThree: com.trifectalabs.raven.v0.models.TrainingZone,
    zoneFour: com.trifectalabs.raven.v0.models.TrainingZone,
    zoneFive: com.trifectalabs.raven.v0.models.TrainingZone,
    createdAt: _root_.org.joda.time.DateTime
  )

  /**
   * Form used to update user training zones
   */
  case class TrainingZonesForm(
    zoneOne: _root_.scala.Option[com.trifectalabs.raven.v0.models.TrainingZone] = None,
    zoneTwo: _root_.scala.Option[com.trifectalabs.raven.v0.models.TrainingZone] = None,
    zoneThree: _root_.scala.Option[com.trifectalabs.raven.v0.models.TrainingZone] = None,
    zoneFour: _root_.scala.Option[com.trifectalabs.raven.v0.models.TrainingZone] = None,
    zoneFive: _root_.scala.Option[com.trifectalabs.raven.v0.models.TrainingZone] = None
  )

  /**
   * Describes the length of an activity
   */
  sealed trait ActivityLength

  object ActivityLength {

    /**
     * Short activity defined by the ActivityType
     */
    case object Short extends ActivityLength { override def toString = "Short" }
    /**
     * Average length activity defined by the ActivityType
     */
    case object Average extends ActivityLength { override def toString = "Average" }
    /**
     * Long activity defined by the ActivityType
     */
    case object Long extends ActivityLength { override def toString = "Long" }

    /**
     * UNDEFINED captures values that are sent either in error or
     * that were added by the server after this library was
     * generated. We want to make it easy and obvious for users of
     * this library to handle this case gracefully.
     *
     * We use all CAPS for the variable name to avoid collisions
     * with the camel cased values above.
     */
    case class UNDEFINED(override val toString: String) extends ActivityLength

    /**
     * all returns a list of all the valid, known values. We use
     * lower case to avoid collisions with the camel cased values
     * above.
     */
    val all = Seq(Short, Average, Long)

    private[this]
    val byName = all.map(x => x.toString.toLowerCase -> x).toMap

    def apply(value: String): ActivityLength = fromString(value).getOrElse(UNDEFINED(value))

    def fromString(value: String): _root_.scala.Option[ActivityLength] = byName.get(value.toLowerCase)

  }

  /**
   * Describes the type of training zones
   */
  sealed trait ZoneType

  object ZoneType {

    /**
     * Heart Rate training zones
     */
    case object Hr extends ZoneType { override def toString = "HR" }
    /**
     * Cycling Power training zones
     */
    case object Power extends ZoneType { override def toString = "Power" }
    /**
     * Running Pace training zones
     */
    case object Pace extends ZoneType { override def toString = "Pace" }

    /**
     * UNDEFINED captures values that are sent either in error or
     * that were added by the server after this library was
     * generated. We want to make it easy and obvious for users of
     * this library to handle this case gracefully.
     *
     * We use all CAPS for the variable name to avoid collisions
     * with the camel cased values above.
     */
    case class UNDEFINED(override val toString: String) extends ZoneType

    /**
     * all returns a list of all the valid, known values. We use
     * lower case to avoid collisions with the camel cased values
     * above.
     */
    val all = Seq(Hr, Power, Pace)

    private[this]
    val byName = all.map(x => x.toString.toLowerCase -> x).toMap

    def apply(value: String): ZoneType = fromString(value).getOrElse(UNDEFINED(value))

    def fromString(value: String): _root_.scala.Option[ZoneType] = byName.get(value.toLowerCase)

  }

}

package com.trifectalabs.raven.v0.models {

  package object json {
    import play.api.libs.json.__
    import play.api.libs.json.JsString
    import play.api.libs.json.Writes
    import play.api.libs.functional.syntax._
    import com.trifectalabs.osprey.v0.models.json._
    import com.trifectalabs.raven.v0.models.json._

    private[v0] implicit val jsonReadsUUID = __.read[String].map(java.util.UUID.fromString)

    private[v0] implicit val jsonWritesUUID = new Writes[java.util.UUID] {
      def writes(x: java.util.UUID) = JsString(x.toString)
    }

    private[v0] implicit val jsonReadsJodaDateTime = __.read[String].map { str =>
      import org.joda.time.format.ISODateTimeFormat.dateTimeParser
      dateTimeParser.parseDateTime(str)
    }

    private[v0] implicit val jsonWritesJodaDateTime = new Writes[org.joda.time.DateTime] {
      def writes(x: org.joda.time.DateTime) = {
        import org.joda.time.format.ISODateTimeFormat.dateTime
        val str = dateTime.print(x)
        JsString(str)
      }
    }

    implicit val jsonReadsRavenActivityLength = new play.api.libs.json.Reads[com.trifectalabs.raven.v0.models.ActivityLength] {
      def reads(js: play.api.libs.json.JsValue): play.api.libs.json.JsResult[com.trifectalabs.raven.v0.models.ActivityLength] = {
        js match {
          case v: play.api.libs.json.JsString => play.api.libs.json.JsSuccess(com.trifectalabs.raven.v0.models.ActivityLength(v.value))
          case _ => {
            (js \ "value").validate[String] match {
              case play.api.libs.json.JsSuccess(v, _) => play.api.libs.json.JsSuccess(com.trifectalabs.raven.v0.models.ActivityLength(v))
              case err: play.api.libs.json.JsError => err
            }
          }
        }
      }
    }

    def jsonWritesRavenActivityLength(obj: com.trifectalabs.raven.v0.models.ActivityLength) = {
      play.api.libs.json.JsString(obj.toString)
    }

    def jsObjectActivityLength(obj: com.trifectalabs.raven.v0.models.ActivityLength) = {
      play.api.libs.json.Json.obj("value" -> play.api.libs.json.JsString(obj.toString))
    }

    implicit def jsonWritesRavenActivityLength: play.api.libs.json.Writes[ActivityLength] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.ActivityLength] {
        def writes(obj: com.trifectalabs.raven.v0.models.ActivityLength) = {
          jsonWritesRavenActivityLength(obj)
        }
      }
    }

    implicit val jsonReadsRavenZoneType = new play.api.libs.json.Reads[com.trifectalabs.raven.v0.models.ZoneType] {
      def reads(js: play.api.libs.json.JsValue): play.api.libs.json.JsResult[com.trifectalabs.raven.v0.models.ZoneType] = {
        js match {
          case v: play.api.libs.json.JsString => play.api.libs.json.JsSuccess(com.trifectalabs.raven.v0.models.ZoneType(v.value))
          case _ => {
            (js \ "value").validate[String] match {
              case play.api.libs.json.JsSuccess(v, _) => play.api.libs.json.JsSuccess(com.trifectalabs.raven.v0.models.ZoneType(v))
              case err: play.api.libs.json.JsError => err
            }
          }
        }
      }
    }

    def jsonWritesRavenZoneType(obj: com.trifectalabs.raven.v0.models.ZoneType) = {
      play.api.libs.json.JsString(obj.toString)
    }

    def jsObjectZoneType(obj: com.trifectalabs.raven.v0.models.ZoneType) = {
      play.api.libs.json.Json.obj("value" -> play.api.libs.json.JsString(obj.toString))
    }

    implicit def jsonWritesRavenZoneType: play.api.libs.json.Writes[ZoneType] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.ZoneType] {
        def writes(obj: com.trifectalabs.raven.v0.models.ZoneType) = {
          jsonWritesRavenZoneType(obj)
        }
      }
    }

    implicit def jsonReadsRavenActivityZones: play.api.libs.json.Reads[ActivityZones] = {
      (
        (__ \ "activityID").read[_root_.java.util.UUID] and
        (__ \ "zoneType").read[com.trifectalabs.raven.v0.models.ZoneType] and
        (__ \ "zoneOne").read[Int] and
        (__ \ "zoneTwo").read[Int] and
        (__ \ "zoneThree").read[Int] and
        (__ \ "zoneFour").read[Int] and
        (__ \ "zoneFive").read[Int]
      )(ActivityZones.apply _)
    }

    def jsObjectActivityZones(obj: com.trifectalabs.raven.v0.models.ActivityZones) = {
      play.api.libs.json.Json.obj(
        "activityID" -> play.api.libs.json.JsString(obj.activityID.toString),
        "zoneType" -> play.api.libs.json.JsString(obj.zoneType.toString),
        "zoneOne" -> play.api.libs.json.JsNumber(obj.zoneOne),
        "zoneTwo" -> play.api.libs.json.JsNumber(obj.zoneTwo),
        "zoneThree" -> play.api.libs.json.JsNumber(obj.zoneThree),
        "zoneFour" -> play.api.libs.json.JsNumber(obj.zoneFour),
        "zoneFive" -> play.api.libs.json.JsNumber(obj.zoneFive)
      )
    }

    implicit def jsonWritesRavenActivityZones: play.api.libs.json.Writes[ActivityZones] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.ActivityZones] {
        def writes(obj: com.trifectalabs.raven.v0.models.ActivityZones) = {
          jsObjectActivityZones(obj)
        }
      }
    }

    implicit def jsonReadsRavenHealthCheck: play.api.libs.json.Reads[HealthCheck] = {
      (__ \ "status").read[String].map { x => new HealthCheck(status = x) }
    }

    def jsObjectHealthCheck(obj: com.trifectalabs.raven.v0.models.HealthCheck) = {
      play.api.libs.json.Json.obj(
        "status" -> play.api.libs.json.JsString(obj.status)
      )
    }

    implicit def jsonWritesRavenHealthCheck: play.api.libs.json.Writes[HealthCheck] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.HealthCheck] {
        def writes(obj: com.trifectalabs.raven.v0.models.HealthCheck) = {
          jsObjectHealthCheck(obj)
        }
      }
    }

    implicit def jsonReadsRavenTrainingPlanActivity: play.api.libs.json.Reads[TrainingPlanActivity] = {
      (
        (__ \ "id").read[_root_.java.util.UUID] and
        (__ \ "userID").read[_root_.java.util.UUID] and
        (__ \ "activityType").read[com.trifectalabs.osprey.v0.models.ActivityType] and
        (__ \ "distance").readNullable[Double] and
        (__ \ "time").readNullable[Double] and
        (__ \ "elevation").readNullable[Double] and
        (__ \ "activityID").readNullable[_root_.java.util.UUID] and
        (__ \ "calendarEventID").readNullable[String] and
        (__ \ "polyline").readNullable[String] and
        (__ \ "scheduledAt").readNullable[_root_.org.joda.time.DateTime] and
        (__ \ "createdAt").read[_root_.org.joda.time.DateTime]
      )(TrainingPlanActivity.apply _)
    }

    def jsObjectTrainingPlanActivity(obj: com.trifectalabs.raven.v0.models.TrainingPlanActivity) = {
      play.api.libs.json.Json.obj(
        "id" -> play.api.libs.json.JsString(obj.id.toString),
        "userID" -> play.api.libs.json.JsString(obj.userID.toString),
        "activityType" -> play.api.libs.json.JsString(obj.activityType.toString),
        "createdAt" -> play.api.libs.json.JsString(_root_.org.joda.time.format.ISODateTimeFormat.dateTime.print(obj.createdAt))
      ) ++ (obj.distance match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("distance" -> play.api.libs.json.JsNumber(x))
      }) ++
      (obj.time match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("time" -> play.api.libs.json.JsNumber(x))
      }) ++
      (obj.elevation match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("elevation" -> play.api.libs.json.JsNumber(x))
      }) ++
      (obj.activityID match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("activityID" -> play.api.libs.json.JsString(x.toString))
      }) ++
      (obj.calendarEventID match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("calendarEventID" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.polyline match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("polyline" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.scheduledAt match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("scheduledAt" -> play.api.libs.json.JsString(_root_.org.joda.time.format.ISODateTimeFormat.dateTime.print(x)))
      })
    }

    implicit def jsonWritesRavenTrainingPlanActivity: play.api.libs.json.Writes[TrainingPlanActivity] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.TrainingPlanActivity] {
        def writes(obj: com.trifectalabs.raven.v0.models.TrainingPlanActivity) = {
          jsObjectTrainingPlanActivity(obj)
        }
      }
    }

    implicit def jsonReadsRavenTrainingZone: play.api.libs.json.Reads[TrainingZone] = {
      (
        (__ \ "lower").read[Double] and
        (__ \ "upper").read[Double]
      )(TrainingZone.apply _)
    }

    def jsObjectTrainingZone(obj: com.trifectalabs.raven.v0.models.TrainingZone) = {
      play.api.libs.json.Json.obj(
        "lower" -> play.api.libs.json.JsNumber(obj.lower),
        "upper" -> play.api.libs.json.JsNumber(obj.upper)
      )
    }

    implicit def jsonWritesRavenTrainingZone: play.api.libs.json.Writes[TrainingZone] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.TrainingZone] {
        def writes(obj: com.trifectalabs.raven.v0.models.TrainingZone) = {
          jsObjectTrainingZone(obj)
        }
      }
    }

    implicit def jsonReadsRavenTrainingZones: play.api.libs.json.Reads[TrainingZones] = {
      (
        (__ \ "userID").read[_root_.java.util.UUID] and
        (__ \ "zoneType").read[com.trifectalabs.raven.v0.models.ZoneType] and
        (__ \ "zoneOne").read[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneTwo").read[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneThree").read[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneFour").read[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneFive").read[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "createdAt").read[_root_.org.joda.time.DateTime]
      )(TrainingZones.apply _)
    }

    def jsObjectTrainingZones(obj: com.trifectalabs.raven.v0.models.TrainingZones) = {
      play.api.libs.json.Json.obj(
        "userID" -> play.api.libs.json.JsString(obj.userID.toString),
        "zoneType" -> play.api.libs.json.JsString(obj.zoneType.toString),
        "zoneOne" -> jsObjectTrainingZone(obj.zoneOne),
        "zoneTwo" -> jsObjectTrainingZone(obj.zoneTwo),
        "zoneThree" -> jsObjectTrainingZone(obj.zoneThree),
        "zoneFour" -> jsObjectTrainingZone(obj.zoneFour),
        "zoneFive" -> jsObjectTrainingZone(obj.zoneFive),
        "createdAt" -> play.api.libs.json.JsString(_root_.org.joda.time.format.ISODateTimeFormat.dateTime.print(obj.createdAt))
      )
    }

    implicit def jsonWritesRavenTrainingZones: play.api.libs.json.Writes[TrainingZones] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.TrainingZones] {
        def writes(obj: com.trifectalabs.raven.v0.models.TrainingZones) = {
          jsObjectTrainingZones(obj)
        }
      }
    }

    implicit def jsonReadsRavenTrainingZonesForm: play.api.libs.json.Reads[TrainingZonesForm] = {
      (
        (__ \ "zoneOne").readNullable[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneTwo").readNullable[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneThree").readNullable[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneFour").readNullable[com.trifectalabs.raven.v0.models.TrainingZone] and
        (__ \ "zoneFive").readNullable[com.trifectalabs.raven.v0.models.TrainingZone]
      )(TrainingZonesForm.apply _)
    }

    def jsObjectTrainingZonesForm(obj: com.trifectalabs.raven.v0.models.TrainingZonesForm) = {
      (obj.zoneOne match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("zoneOne" -> jsObjectTrainingZone(x))
      }) ++
      (obj.zoneTwo match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("zoneTwo" -> jsObjectTrainingZone(x))
      }) ++
      (obj.zoneThree match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("zoneThree" -> jsObjectTrainingZone(x))
      }) ++
      (obj.zoneFour match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("zoneFour" -> jsObjectTrainingZone(x))
      }) ++
      (obj.zoneFive match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("zoneFive" -> jsObjectTrainingZone(x))
      })
    }

    implicit def jsonWritesRavenTrainingZonesForm: play.api.libs.json.Writes[TrainingZonesForm] = {
      new play.api.libs.json.Writes[com.trifectalabs.raven.v0.models.TrainingZonesForm] {
        def writes(obj: com.trifectalabs.raven.v0.models.TrainingZonesForm) = {
          jsObjectTrainingZonesForm(obj)
        }
      }
    }
  }
}

package com.trifectalabs.raven.v0 {

  object Bindables {

    import play.api.mvc.{PathBindable, QueryStringBindable}
    import org.joda.time.{DateTime, LocalDate}
    import org.joda.time.format.ISODateTimeFormat
    import com.trifectalabs.raven.v0.models._

    // Type: date-time-iso8601
    implicit val pathBindableTypeDateTimeIso8601 = new PathBindable.Parsing[org.joda.time.DateTime](
      ISODateTimeFormat.dateTimeParser.parseDateTime(_), _.toString, (key: String, e: Exception) => s"Error parsing date time $key. Example: 2014-04-29T11:56:52Z"
    )

    implicit val queryStringBindableTypeDateTimeIso8601 = new QueryStringBindable.Parsing[org.joda.time.DateTime](
      ISODateTimeFormat.dateTimeParser.parseDateTime(_), _.toString, (key: String, e: Exception) => s"Error parsing date time $key. Example: 2014-04-29T11:56:52Z"
    )

    // Type: date-iso8601
    implicit val pathBindableTypeDateIso8601 = new PathBindable.Parsing[org.joda.time.LocalDate](
      ISODateTimeFormat.yearMonthDay.parseLocalDate(_), _.toString, (key: String, e: Exception) => s"Error parsing date $key. Example: 2014-04-29"
    )

    implicit val queryStringBindableTypeDateIso8601 = new QueryStringBindable.Parsing[org.joda.time.LocalDate](
      ISODateTimeFormat.yearMonthDay.parseLocalDate(_), _.toString, (key: String, e: Exception) => s"Error parsing date $key. Example: 2014-04-29"
    )

    // Enum: ActivityLength
    private[this] val enumActivityLengthNotFound = (key: String, e: Exception) => s"Unrecognized $key, should be one of ${com.trifectalabs.raven.v0.models.ActivityLength.all.mkString(", ")}"

    implicit val pathBindableEnumActivityLength = new PathBindable.Parsing[com.trifectalabs.raven.v0.models.ActivityLength] (
      ActivityLength.fromString(_).get, _.toString, enumActivityLengthNotFound
    )

    implicit val queryStringBindableEnumActivityLength = new QueryStringBindable.Parsing[com.trifectalabs.raven.v0.models.ActivityLength](
      ActivityLength.fromString(_).get, _.toString, enumActivityLengthNotFound
    )

    // Enum: ZoneType
    private[this] val enumZoneTypeNotFound = (key: String, e: Exception) => s"Unrecognized $key, should be one of ${com.trifectalabs.raven.v0.models.ZoneType.all.mkString(", ")}"

    implicit val pathBindableEnumZoneType = new PathBindable.Parsing[com.trifectalabs.raven.v0.models.ZoneType] (
      ZoneType.fromString(_).get, _.toString, enumZoneTypeNotFound
    )

    implicit val queryStringBindableEnumZoneType = new QueryStringBindable.Parsing[com.trifectalabs.raven.v0.models.ZoneType](
      ZoneType.fromString(_).get, _.toString, enumZoneTypeNotFound
    )

  }

}
